# 🌿 AI Crop Disease Detection (FINAL STABLE VERSION) hg
# Author: Gulam N Chabbi

import streamlit as st
from transformers import pipeline
from PIL import Image
import pandas as pd

# ---------------- PAGE CONFIG ----------------
st.set_page_config(
    page_title="AI Crop Disease Detection",
    page_icon="🌿",
    layout="wide"
)

# ---------------- SESSION STATE ----------------
if "results" not in st.session_state:
    st.session_state.results = None

# ---------------- PREMIUM UI ----------------
def load_css():
    st.markdown("""
    <style>
    .stApp {
        background-image: url("https://images.unsplash.com/photo-1470115636492-6d2b56f9146d?q=80&w=1920");
        background-size: cover;
        background-position: center;
        background-attachment: fixed;
    }

    .stApp::before {
        content: "";
        position: fixed;
        top: 0; left: 0;
        width: 100%; height: 100%;
        background: rgba(0,0,0,0.55);
        z-index: 0;
    }

    .main { position: relative; z-index: 1; }

    .card {
        background: rgba(255,255,255,0.08);
        padding: 25px;
        border-radius: 18px;
        backdrop-filter: blur(18px);
        box-shadow: 0 8px 32px rgba(0,0,0,0.4);
        margin-bottom: 20px;
    }

    h1,h2,h3,h4,p,label { color: white !important; }

    .stButton>button {
        background: linear-gradient(45deg, #00c853, #b2ff59);
        color: black;
        border-radius: 10px;
        font-weight: bold;
    }

    section[data-testid="stSidebar"] {
        background: rgba(0,0,0,0.6);
    }
    </style>
    """, unsafe_allow_html=True)

load_css()

# ---------------- SIDEBAR ----------------
st.sidebar.title("⚙️ Settings")
show_all_predictions = st.sidebar.toggle("Show all predictions", True)
show_confidence = st.sidebar.toggle("Show confidence", True)

st.sidebar.markdown("---")
st.sidebar.warning("⚠️ Best results for bean leaf diseases")

# ---------------- SAFE MODEL LOAD ----------------
@st.cache_resource
def load_model():
    try:
        return pipeline(
            "image-classification",
            model="nateraw/vit-base-beans"
        )
    except Exception:
        return pipeline(
            "image-classification",
            model="google/vit-base-patch16-224"
        )

# ---------------- HEADER ----------------
st.markdown("<h1 style='text-align:center;'>🌿 AI Crop Disease Detection</h1>", unsafe_allow_html=True)
st.markdown("<p style='text-align:center;'>Upload a leaf image and detect disease using AI</p>", unsafe_allow_html=True)

# ---------------- UPLOAD ----------------
st.markdown('<div class="card">', unsafe_allow_html=True)
uploaded_file = st.file_uploader("📤 Upload Leaf Image", type=["jpg","jpeg","png"])
st.markdown('</div>', unsafe_allow_html=True)

# ---------------- MAIN ----------------
if uploaded_file:
    image = Image.open(uploaded_file).convert("RGB")

    col1, col2 = st.columns([1, 1.2])

    # IMAGE
    with col1:
        st.markdown('<div class="card">', unsafe_allow_html=True)
        st.image(image, caption="Uploaded Image", use_container_width=True)
        st.markdown('</div>', unsafe_allow_html=True)

    # ANALYSIS
    with col2:
        st.markdown('<div class="card">', unsafe_allow_html=True)

        if st.button("🚀 Run AI Analysis"):
            with st.spinner("Analyzing image..."):
                model = load_model()
                st.session_state.results = model(image)

        results = st.session_state.results

        if results is not None:
            top = results[0]

            label_raw = top["label"]
            score = top["score"] * 100

            label = label_raw.replace("_", " ").replace("___", " - ").title()

            st.success(f"🌱 {label}")

            if show_confidence:
                st.progress(int(score))
                st.write(f"Confidence: {score:.2f}%")

            st.markdown("### 📖 Description")
            st.write("AI-detected plant condition. For precise diagnosis, consult an agriculture expert.")

            st.markdown("### 💊 Treatment")
            st.info("Apply suitable fungicide/pesticide based on disease type.")

            # REPORT
            report = f"""
Crop Disease Detection Report

Disease: {label}
Confidence: {score:.2f}%

Generated by AI System
Author: Gulam N Chabbi
"""
            st.download_button("📄 Download Report", report)

        st.markdown('</div>', unsafe_allow_html=True)

    # ---------------- PREDICTIONS ----------------
    if show_all_predictions and results is not None:
        st.markdown('<div class="card">', unsafe_allow_html=True)

        chart_data = pd.DataFrame([
            {
                "Disease": r["label"].replace("_", " "),
                "Probability": r["score"] * 100
            }
            for r in results
        ])

        st.markdown("### 📊 Detailed Predictions")
        st.dataframe(chart_data, use_container_width=True)
        st.bar_chart(chart_data.set_index("Disease"))

        st.markdown('</div>', unsafe_allow_html=True)

# ---------------- FOOTER ----------------
st.markdown("---")
st.markdown("<p style='text-align:center;'>🚀 Developed by <b>Gulam N Chabbi</b></p>", unsafe_allow_html=True)
